import os
import sys
import traceback
from pathlib import Path

# =============================================================================
#  MMS AGENT - DEV AGENT (DSL EXECUTION ENGINE)
# =============================================================================

# agent internal modules
AGENT_ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = AGENT_ROOT.parent  # project/mms_agent/..

sys.path.insert(0, str(PROJECT_ROOT))

from mms_agent.agent.agent_scope import validate_write, validate_read
from mms_agent.agent import agent_scope


DOCS_DIR = PROJECT_ROOT / "docs"
PROJECT_TREE = DOCS_DIR / "PROJECT_TREE.md"


# =============================================================================
#   Utility: refresh project tree
# =============================================================================
def refresh_project_tree():
    out = []

    def walk(p: Path, prefix=""):
        try:
            items = sorted(p.iterdir(), key=lambda x: (x.is_file(), x.name.lower()))
        except:
            return
        for item in items:
            if item.name.startswith(".") or item.name == "__pycache__":
                continue
            out.append(prefix + ("📁 " if item.is_dir() else "📄 ") + item.name)
            if item.is_dir():
                walk(item, prefix + "    ")

    out.append("# PROJECT TREE\n")
    out.append("Generated by mms_agent\n\n")
    out.append("```\n")
    walk(PROJECT_ROOT)
    out.append("```\n")

    PROJECT_TREE.parent.mkdir(parents=True, exist_ok=True)
    PROJECT_TREE.write_text("\n".join(out), encoding="utf-8")

    print("PROJECT_TREE.md 已更新")


# =============================================================================
#   DSL Interpreter
# =============================================================================

class DSLInterpreter:

    def __init__(self):
        self.current_file_path = None
        self.collecting = False
        self.buffer = []

    # -------------------------------------------------------------------------
    #  parse & execute task file
    # -------------------------------------------------------------------------
    def run(self, text: str):
        lines = text.splitlines()

        for line in lines:
            stripped = line.strip()

            # ===== 写入文件（开始） =====
            if stripped.startswith("写入文件"):
                # flush previous
                self._flush_write()

                # new file path
                path = stripped.replace("写入文件", "").replace("；", "").strip()
                self.current_file_path = PROJECT_ROOT / path
                self.buffer = []
                self.collecting = False
                print(f"[写入文件] {self.current_file_path}")
                continue

            # ===== 写入文件内容（进入 collecting） =====
            if stripped.startswith("内容为"):
                self.collecting = True
                continue

            # ===== collecting mode =====
            if self.collecting:
                self.buffer.append(line)
                continue

            # ===== 创建目录 =====
            if stripped.startswith("创建目录"):
                dir_path = stripped.replace("创建目录", "").replace("；", "").strip()
                abs_path = PROJECT_ROOT / dir_path
                self._create_dir(abs_path)
                continue

            # ===== 删除文件 =====
            if stripped.startswith("删除文件"):
                file_path = stripped.replace("删除文件", "").replace("；", "").strip()
                abs_path = PROJECT_ROOT / file_path
                self._delete_file(abs_path)
                continue

            # ===== 移动文件 =====
            if "移动文件" in stripped and "→" in stripped:
                src, dst = stripped.replace("移动文件", "").replace("；", "").split("→")
                self._move_file(PROJECT_ROOT / src.strip(), PROJECT_ROOT / dst.strip())
                continue

            # ===== 复制文件 =====
            if "复制文件" in stripped and "→" in stripped:
                src, dst = stripped.replace("复制文件", "").replace("；", "").split("→")
                self._copy_file(PROJECT_ROOT / src.strip(), PROJECT_ROOT / dst.strip())
                continue

        # flush tail writing
        self._flush_write()

        refresh_project_tree()


    # -------------------------------------------------------------------------
    #  create dir
    # -------------------------------------------------------------------------
    def _create_dir(self, path: Path):
        try:
            validate_write(str(path))
            path.mkdir(parents=True, exist_ok=True)
            print(f"[创建目录] {path}")
        except Exception as e:
            print(f"❌ 创建目录失败 {path}: {e}")

    # -------------------------------------------------------------------------
    #  delete file
    # -------------------------------------------------------------------------
    def _delete_file(self, path: Path):
        try:
            if path.exists():
                validate_write(str(path))
                path.unlink()
                print(f"[删除文件] {path}")
            else:
                print(f"[删除文件] 找不到文件 {path}")
        except Exception as e:
            print(f"❌ 删除失败 {path}: {e}")

    # -------------------------------------------------------------------------
    #  move file
    # -------------------------------------------------------------------------
    def _move_file(self, src: Path, dst: Path):
        try:
            validate_write(str(src))
            validate_write(str(dst))
            dst.parent.mkdir(parents=True, exist_ok=True)
            src.rename(dst)
            print(f"[移动文件] {src} → {dst}")
        except Exception as e:
            print(f"❌ 移动失败 {src} → {dst}: {e}")

    # -------------------------------------------------------------------------
    #  copy file
    # -------------------------------------------------------------------------
    def _copy_file(self, src: Path, dst: Path):
        import shutil
        try:
            validate_read(str(src))
            validate_write(str(dst))
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy(src, dst)
            print(f"[复制文件] {src} → {dst}")
        except Exception as e:
            print(f"❌ 复制失败 {src} → {dst}: {e}")

    # -------------------------------------------------------------------------
    #  flush write buffer
    # -------------------------------------------------------------------------
    def _flush_write(self):
        if not self.current_file_path:
            return
        try:
            target = self.current_file_path
            validate_write(str(target))
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text("\n".join(self.buffer), encoding="utf-8")
            print(f"[写入成功] {target}")
        except Exception as e:
            print(f"❌ 写入失败 {target}: {e}")
        finally:
            self.current_file_path = None
            self.collecting = False
            self.buffer = []


# =============================================================================
#  command: run DSL task file
# =============================================================================

def run_task(task_file: Path):
    if not task_file.exists():
        print("任务文件不存在:", task_file)
        return

    text = task_file.read_text(encoding="utf-8")
    print(f"===== 执行任务文件：{task_file} =====\n")

    interpreter = DSLInterpreter()
    interpreter.run(text)

    print("\n===== 任务执行完毕 =====")


# =============================================================================
#  main entry
# =============================================================================

def main():
    if len(sys.argv) < 2:
        print("用法: python dev_agent.py \"执行任务文件 docs/xxx.md\"")
        return

    cmd = sys.argv[1].strip()

    if cmd.startswith("执行任务文件"):
        _, path = cmd.split(" ", 1)
        run_task(Path(path.strip()))
        return

    print("无法识别指令：", cmd)


if __name__ == "__main__":
    main()
